"""Initial migration

Revision ID: 8b67ca27578e
Revises: 
Create Date: 2025-05-04 13:44:24.759651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b67ca27578e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_takings',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('till_read', sa.Float(), nullable=True),
    sa.Column('eftpos_total', sa.Float(), nullable=True),
    sa.Column('portable_eftpos_total', sa.Float(), nullable=True),
    sa.Column('amex', sa.Float(), nullable=True),
    sa.Column('diners', sa.Float(), nullable=True),
    sa.Column('account_charges', sa.Float(), nullable=True),
    sa.Column('total_cash', sa.Float(), nullable=True),
    sa.Column('points_redeemed', sa.Float(), nullable=True),
    sa.Column('customer_count', sa.Integer(), nullable=True),
    sa.Column('safe_float_open', sa.Text(), nullable=True),
    sa.Column('safe_float_close', sa.Text(), nullable=True),
    sa.Column('till_float_open', sa.Text(), nullable=True),
    sa.Column('till_float_close_before_makeup', sa.Text(), nullable=True),
    sa.Column('till_float_makeup', sa.Text(), nullable=True),
    sa.Column('variance', sa.Float(), nullable=True),
    sa.Column('settled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_takings')
    # ### end Alembic commands ###
